"""Add previous voiceBridge table.

Revision ID: 41d1692ca6c4
Revises: c25342fd2428
Create Date: 2025-03-27 07:42:10.563875
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "41d1692ca6c4"
down_revision = "c25342fd2428"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "previous_voice_bridge",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("voiceBridge", sa.Unicode(length=50), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("voiceBridge"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("previous_voice_bridge")
    # ### end Alembic commands ###
