"""Add date and favorite in meeting.

Revision ID: 44cab47dbc9b
Revises: 9d4ba8cf710a
Create Date: 2025-02-27 12:47:23.430229
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "44cab47dbc9b"
down_revision = "9d4ba8cf710a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meeting", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("is_favorite", sa.Boolean, nullable=True))

    op.execute("UPDATE meeting SET created_at = CURRENT_TIMESTAMP")
    op.execute("UPDATE meeting SET updated_at = CURRENT_TIMESTAMP")
    op.execute("UPDATE meeting SET is_favorite = 'FALSE'")

    with op.batch_alter_table("meeting", schema=None) as batch_op:
        batch_op.alter_column("created_at", nullable=False)
        batch_op.alter_column("updated_at", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meeting", schema=None) as batch_op:
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("is_favorite")
    # ### end Alembic commands ###
