"""GuestPolicy migration

Revision ID: 7d80b9223a1e
Revises: 54f71a7705a8
Create Date: 2023-02-28 14:29:28.456201

"""
from alembic import op
import sqlalchemy as sa

import os
import sys

current = os.path.dirname(os.path.realpath(__file__))
parent = os.path.dirname(current)
sys.path.append(parent)

import alembic_helpers


# revision identifiers, used by Alembic.
revision = "7d80b9223a1e"
down_revision = "54f71a7705a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not alembic_helpers.table_has_column("meeting", "guestPolicy"):
        op.add_column("meeting", sa.Column("guestPolicy", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if alembic_helpers.table_has_column("meeting", "guestPolicy"):
        op.drop_column("meeting", "guestPolicy")
    # ### end Alembic commands ###
