"""add last_connection_utc_datetime

Revision ID: 8fe077ecfb10
Revises: 9aac3b5e1582
Create Date: 2022-08-12 09:09:47.674373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import os
import sys

current = os.path.dirname(os.path.realpath(__file__))
parent = os.path.dirname(current)
sys.path.append(parent)

import alembic_helpers


# revision identifiers, used by Alembic.
revision = "8fe077ecfb10"
down_revision = "9aac3b5e1582"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not alembic_helpers.table_has_column("user", "last_connection_utc_datetime"):
        op.add_column(
            "user",
            sa.Column("last_connection_utc_datetime", sa.DateTime(), nullable=True),
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if alembic_helpers.table_has_column("user", "last_connection_utc_datetime"):
        op.drop_column("user", "last_connection_utc_datetime")
    # ### end Alembic commands ###
