"""add date in meeting

Revision ID: 44cab47dbc9b
Revises: 9d4ba8cf710a
Create Date: 2025-02-27 12:47:23.430229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44cab47dbc9b'
down_revision = '9d4ba8cf710a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE meeting SET created_at = NOW()")
    op.execute("UPDATE meeting SET updated_at = NOW()")
    op.execute("ALTER TABLE meeting ALTER COLUMN updated_at SET NOT NULL")
    op.execute("ALTER TABLE meeting ALTER COLUMN updated_at SET NOT NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
    # ### end Alembic commands ###
