"""VoiceBridge managed by b3desk.

Revision ID: c25342fd2428
Revises: 44cab47dbc9b
Create Date: 2025-03-25 08:23:29.169319
"""

import random

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session
from sqlalchemy.sql import select
from sqlalchemy.sql import update

# revision identifiers, used by Alembic.
revision = "c25342fd2428"
down_revision = "44cab47dbc9b"
branch_labels = None
depends_on = None


def pin_generation(pins):
    generate_random_pin = random.randint(100000000, 999999999)
    return create_unique_pin(generate_random_pin, pins)


def create_unique_pin(pin, pins):
    pin_string = str(pin)
    if pin_string not in pins:
        pins.append(pin_string)
        return pin_string
    else:
        pin += 1
        return create_unique_pin(pin, pins)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind)
    meeting = sa.table(
        "meeting", sa.column("id", sa.Integer), sa.column("voiceBridge", sa.String)
    )
    pins = []
    for (meeting_id,) in session.execute(select(meeting.c.id)):
        pin = pin_generation(pins)
        session.execute(
            update(meeting).where(meeting.c.id == meeting_id).values(voiceBridge=pin)
        )
    session.commit()
    with op.batch_alter_table("meeting", schema=None) as batch_op:
        batch_op.alter_column("voiceBridge", nullable=False)
        batch_op.create_unique_constraint("uq_meeting_voicebridge", ["voiceBridge"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meeting", schema=None) as batch_op:
        batch_op.drop_constraint("uq_meeting_voicebridge", type_="unique")
        batch_op.alter_column("voiceBridge", nullable=True)
    bind = op.get_bind()
    session = Session(bind)
    meeting = sa.table("meeting", sa.column("voiceBridge", sa.String))
    session.execute(update(meeting).values(voiceBridge=None))
    session.commit()
    # ### end Alembic commands ###
