"""Parametrage affichage bbb.

Revision ID: d8fdc258f263
Revises: a3a6e932b2ae
Create Date: 2026-07-24 13:01:45.610029

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d8fdc258f263"
down_revision = "a3a6e932b2ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meeting", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("hidePresentationOnJoin", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("showParticipantsOnLogin", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("showPublicChatOnLogin", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("showSessionDetailsOnJoin", sa.Boolean(), nullable=True)
        )
        batch_op.alter_column(
            "attendeePW",
            existing_type=postgresql.BYTEA(),
            type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "moderatorPW",
            existing_type=postgresql.BYTEA(),
            type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
            existing_nullable=True,
        )

    with op.batch_alter_table("meeting_files", schema=None) as batch_op:
        batch_op.alter_column(
            "title", existing_type=sa.VARCHAR(length=4096), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meeting_files", schema=None) as batch_op:
        batch_op.alter_column(
            "title", existing_type=sa.VARCHAR(length=4096), nullable=False
        )

    with op.batch_alter_table("meeting", schema=None) as batch_op:
        batch_op.alter_column(
            "moderatorPW",
            existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
            type_=postgresql.BYTEA(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "attendeePW",
            existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
            type_=postgresql.BYTEA(),
            existing_nullable=True,
        )
        batch_op.drop_column("showSessionDetailsOnJoin")
        batch_op.drop_column("showPublicChatOnLogin")
        batch_op.drop_column("showParticipantsOnLogin")
        batch_op.drop_column("hidePresentationOnJoin")

    # ### end Alembic commands ###
