"""Parametrage affichage bbb.

Revision ID: d8fdc258f263
Revises: a3203f74e042
Create Date: 2026-07-24 13:01:45.610029

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d8fdc258f263"
down_revision = "a3203f74e042"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meeting", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "showPresentationOnJoin",
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "showParticipantsOnLogin",
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "showPublicChatOnLogin",
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "showSessionDetailsOnJoin",
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meeting", schema=None) as batch_op:
        batch_op.drop_column("showSessionDetailsOnJoin")
        batch_op.drop_column("showPublicChatOnLogin")
        batch_op.drop_column("showParticipantsOnLogin")
        batch_op.drop_column("showPresentationOnJoin")

    # ### end Alembic commands ###
