---
name: Documentation
on:
  push:
    branches:
      - production
      - main
  pull_request:
    branches:
      - production
      - main
jobs:
  tests:
    name: ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: Build documentation
        run: uv run --group doc sphinx-build documentation build/sphinx/html
