FROM python:3.14-slim-trixie

COPY --from=ghcr.io/astral-sh/uv:0.5 /uv /uvx /bin/

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV PATH="/opt/.venv/bin:$PATH"

COPY --from=root pyproject.toml uv.lock /opt/
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-install-project --only-group worker --directory /opt --python /usr/local/bin/python

COPY misc/run_celery.sh /opt/
RUN chmod u+x /opt/run_celery.sh

RUN groupadd --gid 1000 celery \
    && useradd --uid 1000 --gid celery --shell /bin/bash celery

WORKDIR /usr/src/app/

USER celery

ENTRYPOINT ["/opt/run_celery.sh"]
